'''
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.

Example 2:

Input: s = "", t = "y"
Output: "y"

Example 3:

Input: s = "a", t = "aa"
Output: "a"

Example 4:

Input: s = "ae", t = "aea"
Output: "a"
'''

class Solution(object):
    def findTheDifference(s: str, t: str) -> str:
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        # if s is none return t 
        # since that is probably the letter that was added
        if s == "":
            return t

        list_t = list(t)

        # iterate s
        for i in list(s):
            # whatever letter it is currently
            # you remove that letter from t
            list_t.remove(i)
            # so whatever is left you return it
        
        return list_t[0]

        # s = list(s)
        # t = list(t)
        # s.sort()
        # t.sort()
        
        # for i in range(len(t)):
        #     if i == len(s):
        #         return t[i]
        #     elif s[i] == t[i]:
        #         continue
        #     else: 
        #         return t[i]


    s = "abcd"
    t = "abcde"
    
    print(findTheDifference(s, t))





    

    
